"""Add warehouse categories and products

Revision ID: f08cac5b5d1e
Revises: 1b1aa25ea5a8
Create Date: 2025-11-22 15:43:46.156549

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f08cac5b5d1e'
down_revision = '1b1aa25ea5a8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('warehouse_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='venookah2'
    )
    op.create_table('warehouse_products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sku', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['venookah2.warehouse_categories.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sku'),
    schema='venookah2'
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_constraint('audit_logs_user_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'], referent_schema='venookah2')

    with op.batch_alter_table('b2b_check_results', schema=None) as batch_op:
        batch_op.drop_constraint('b2b_check_results_user_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'], referent_schema='venookah2')

    with op.batch_alter_table('cart_items', schema=None) as batch_op:
        batch_op.drop_constraint('cart_items_product_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('cart_items_cart_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'carts', ['cart_id'], ['id'], referent_schema='venookah2')
        batch_op.create_foreign_key(None, 'products', ['product_id'], ['id'], referent_schema='venookah2')

    with op.batch_alter_table('carts', schema=None) as batch_op:
        batch_op.drop_constraint('carts_user_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'], referent_schema='venookah2')

    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.drop_constraint('categories_parent_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'categories', ['parent_id'], ['id'], referent_schema='venookah2')

    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.drop_constraint('companies_user_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'], referent_schema='venookah2')

    with op.batch_alter_table('contacts', schema=None) as batch_op:
        batch_op.drop_constraint('contacts_company_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'companies', ['company_id'], ['id'], referent_schema='venookah2')

    with op.batch_alter_table('order_items', schema=None) as batch_op:
        batch_op.drop_constraint('order_items_product_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('order_items_order_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'orders', ['order_id'], ['id'], referent_schema='venookah2')
        batch_op.create_foreign_key(None, 'products', ['product_id'], ['id'], referent_schema='venookah2')

    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_constraint('orders_user_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'], referent_schema='venookah2')

    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_constraint('payments_order_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'orders', ['order_id'], ['id'], referent_schema='venookah2')

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_constraint('products_category_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'categories', ['category_id'], ['id'], referent_schema='venookah2')

    with op.batch_alter_table('shipments', schema=None) as batch_op:
        batch_op.drop_constraint('shipments_order_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'orders', ['order_id'], ['id'], referent_schema='venookah2')

    with op.batch_alter_table('stock_items', schema=None) as batch_op:
        batch_op.drop_constraint('stock_items_product_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'products', ['product_id'], ['id'], referent_schema='venookah2')

    with op.batch_alter_table('warehouse_tasks', schema=None) as batch_op:
        batch_op.drop_constraint('warehouse_tasks_assigned_to_fkey', type_='foreignkey')
        batch_op.drop_constraint('warehouse_tasks_order_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'orders', ['order_id'], ['id'], referent_schema='venookah2')
        batch_op.create_foreign_key(None, 'users', ['assigned_to'], ['id'], referent_schema='venookah2')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('warehouse_tasks', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('warehouse_tasks_order_id_fkey', 'orders', ['order_id'], ['id'])
        batch_op.create_foreign_key('warehouse_tasks_assigned_to_fkey', 'users', ['assigned_to'], ['id'])

    with op.batch_alter_table('stock_items', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('stock_items_product_id_fkey', 'products', ['product_id'], ['id'])

    with op.batch_alter_table('shipments', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('shipments_order_id_fkey', 'orders', ['order_id'], ['id'])

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('products_category_id_fkey', 'categories', ['category_id'], ['id'])

    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('payments_order_id_fkey', 'orders', ['order_id'], ['id'])

    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('orders_user_id_fkey', 'users', ['user_id'], ['id'])

    with op.batch_alter_table('order_items', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('order_items_order_id_fkey', 'orders', ['order_id'], ['id'])
        batch_op.create_foreign_key('order_items_product_id_fkey', 'products', ['product_id'], ['id'])

    with op.batch_alter_table('contacts', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('contacts_company_id_fkey', 'companies', ['company_id'], ['id'])

    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('companies_user_id_fkey', 'users', ['user_id'], ['id'])

    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('categories_parent_id_fkey', 'categories', ['parent_id'], ['id'])

    with op.batch_alter_table('carts', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('carts_user_id_fkey', 'users', ['user_id'], ['id'])

    with op.batch_alter_table('cart_items', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('cart_items_cart_id_fkey', 'carts', ['cart_id'], ['id'])
        batch_op.create_foreign_key('cart_items_product_id_fkey', 'products', ['product_id'], ['id'])

    with op.batch_alter_table('b2b_check_results', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('b2b_check_results_user_id_fkey', 'users', ['user_id'], ['id'])

    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('audit_logs_user_id_fkey', 'users', ['user_id'], ['id'])

    op.drop_table('warehouse_products', schema='venookah2')
    op.drop_table('warehouse_categories', schema='venookah2')
    # ### end Alembic commands ###
